### ISSUE TITLE
Views are being prefixed with .html

### ISSUE THREAD

**Issue by mull** [cehoffman/sinatra-respond_to#15]
I noticed when trying out the gem that my views (such as user.erb) were prefixed with .html, so all of a sudden my views weren't found anymore. Why?

**Comment by cehoffman** [comment]
This has to do with the general way views are organized by url path and respond_to allows several different views for each url. Instead of having to rename views as you use respond_to in an app, it just makes all views have the format in the name. It also follows the rails setup of views since respond_to was made to mimic respond_to from rails.
