### ISSUE TITLE
What should be the format for mobiles? like iPhone's user agent?

### ISSUE THREAD

**Issue by mariozaizar** [cehoffman/sinatra-respond_to#8]
What should be the format for mobiles? like iPhone's user agent?
I'm trying to do something like this:

```
respond_to do |wants|
  wants.mobile  { haml :'mobile/home', :layout => :'mobile/layout' }
  wants.any     { haml :'static/home', :layout => :'static/layout' }
end
```

Right now I've a helper called, mobile_request? that compares the request user agent against iphones and androids.

**Comment by cehoffman** [comment]
Right now this isn't supported because we deal specifically with mime types which mobile isn't really a mime type. Looking at how rails handles this, they allow setting an override value that you can lookup by.  I'll have to give it some thought, but I don't have an immediate solution. The best route may to have a helper that return mobile/static and interpolate that into the render options.

**Comment by mariozaizar** [comment]
Yeah, actually that was my first attempt to solve that. Using a helper:

```
def request_type? do  
  return :mobile if mobile_request?
  return :ajax if request.xhr?
  return :desktop
end
```

And then simulate the respond_to:

```
get '/some/url' do  
  @users = Users.all
  case request_type? do
    when :mobile then haml :mobile
    when :ajax then haml :mobile, false
    else haml :desktop
  end
end
```
